/*
 * Copyright 2026 Julien Bombled
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! Certificates written by the Certificate Generator's code on master at 8a5b8ad, before
//! it moved into sealvault: the same key, names, dates and serials must give the same bytes,
//! RSA PKCS #1 v1.5 being deterministic.
//!
//! The fixtures were printed by a throwaway test added to `certificate_generator.rs` in a
//! checkout of master at 8a5b8ad (`leaf_params` and `base_params` with the C#'s CA
//! extensions, each serial then set to the one below, signed by rcgen with
//! [`TEST_ONLY_RSA_PKCS8_HEX`]), run with
//! `cargo test -p heimdall-core --lib --locked zz_fixture -- --nocapture`.

use std::net::IpAddr;

use sealvault::cert::{self, AltName, Name, Profile, SigningKey, Spec};

/// TEST-ONLY key: a 2048-bit RSA key, PKCS#8 DER in hexadecimal, generated by OpenSSL for
/// this fixture alone. It protects nothing and is used nowhere else; it is here only so
/// that the certificates below can be signed again and compared byte for byte.
const TEST_ONLY_RSA_PKCS8_HEX: &str = "\
    308204bd020100300d06092a864886f70d0101010500048204a7308204a30201000282010100e6acdfd30274\
    c495c0e7498e0205821f93dd5728243f0efff23e84dddde41463eb955af3be2750fac2ffc809e1b33f000d72\
    a1f989e49bb68c2aca7261c9eebce82183cad68a4baf6abf6ccd7d0d018f57506f682dd9815ecdc84d333d6f\
    650a7a377b220120902f92bbfd2346491bdf62c0db40a01506f35326bb810177886249fefa0385e0fde12cd5\
    a2e2659d64e0c444ded5296e4bfd9e9803722ccc7548176162265f921b80106140714547eb1a0bcec4c1b023\
    30f386f5919445b9a23fa19103a5e164020335cebac28066715661d08b2aaa414a8d994cf89e09dc79e07f9a\
    cd6e1a11d63c9f0108fd6239e9d055e08e435af99b8ab0f1fd01fcf0755902030100010282010035a5fb204e\
    2fee108e1ebc82a481b773b4a603c1383cda363896c5bbfc0131a4d38396f59d41f3997e84927789e0704488\
    dc2243b1085416ae9ebd1ac1177fc8bb8c1fe4aae4db195f104a33b863affb30696a9fa61a31f66491b332b9\
    9510c0d10fda395c5dc06af00b7ca21994a340deeccf914629ddc5f58eca8904585285685cf0679a11919562\
    854d66e24ccb06e23631eee776436d6037752f32503626bda5e31cef87c97162066afd786bfdcfd387b520ee\
    d7e2e685ff9b3c6d8719d9e6aef9dc8952159c67b0da6136aef4b8cd5cc56af03af169d0396c122d4e1927b8\
    4382b62ef55c8bb16f57f81e4404661a2f8073492fccb73e2d5b41edea6ae902818100fe665d5b7a96965484\
    de3d5ef220d49c3e48cd95ac442d229b4d1b8e24aabad566a07231477abbac41b43535826cf5c1018ed05386\
    15e7ca614a1a047bbaddfd48348184b5f73453908aa32d86491011e231f8125b051526daaf73ffd02df4344b\
    762ad1666cdc5fec2376a360d5730932034c0fe9ae9b8cf400ff767db0bd6302818100e8204eeab70eaf5177\
    61b6ef9639ba5cf50508a9eaa721fc4ed35d36e900a20b6f126ad225f3d17b228e97d0b71b7bc89bacbf0af8\
    27a8c9ddea991e705900e88ce0360508a5c241bf0b04e76d0fc911ac5ece1619304a25eb569a05c3b44230cc\
    759b9024e37f789025f0036fbce621a02020dd746613861aa6bab5c4d82d130281805afc2361874b7a428a2e\
    adc65a549195bbd4efea1aed5b3328560087eae740e0f7ce6468e986a4be6bd556be67822eb6b3a6ef2d2024\
    8f7cdb24d47f4bfd3e4dcad83486514a3365bba949c90b60f025653fb7d860c345985ad82b658f800ff9f00f\
    382b2235c6ef6b9617654149b5d5d1144accda27bfac3ecc6891694c9fbf0281800d77625ca7860891b75549\
    e1985b7cfe4b90a1320a54ebd9d150ddc583baefabae23e9628ba51b70034f366b7b53f2d86e7f950db3dbc9\
    24fce4d1413ccf4d0830b4092e3d943032d43c756a5f9f5cd0d3a924578fda8752afd6745505477dd78ae4ff\
    c35b007fb2a4da2e94647516fcb86764c0b431ffcbf5dbda5515385d5502818100cbf90c8e73a8e250c85c39\
    03bd07c9dde88165f8a918a2d0b76a286f51d417c1adbb15df81e27c943a64041c6f3c450e01749ff87cf288\
    b204d95cf3e5309ee37e060f3823fe1cb851f2ade75117baff21abe1cd3263d04ca64043b18af15a8fe105c0\
    d8ffaf27cd98cb0ddf0c3053564734233304577ae73dfe53b9d81cd162";

/// A self-signed TLS leaf: CN=server.local, O=Heimdall, C=FR, server.local and 10.0.0.1.
const SELF_SIGNED_HEX: &str = "\
    3082034830820230a00302010202081122334455667708300d06092a864886f70d01010b05003037310b3009\
    0603550406130246523111300f060355040a0c084865696d64616c6c3115301306035504030c0c7365727665\
    722e6c6f63616c301e170d3236303130323033303430355a170d3237303130323033303430355a3037310b30\
    090603550406130246523111300f060355040a0c084865696d64616c6c3115301306035504030c0c73657276\
    65722e6c6f63616c30820122300d06092a864886f70d01010105000382010f003082010a0282010100e6acdf\
    d30274c495c0e7498e0205821f93dd5728243f0efff23e84dddde41463eb955af3be2750fac2ffc809e1b33f\
    000d72a1f989e49bb68c2aca7261c9eebce82183cad68a4baf6abf6ccd7d0d018f57506f682dd9815ecdc84d\
    333d6f650a7a377b220120902f92bbfd2346491bdf62c0db40a01506f35326bb810177886249fefa0385e0fd\
    e12cd5a2e2659d64e0c444ded5296e4bfd9e9803722ccc7548176162265f921b80106140714547eb1a0bcec4\
    c1b02330f386f5919445b9a23fa19103a5e164020335cebac28066715661d08b2aaa414a8d994cf89e09dc79\
    e07f9acd6e1a11d63c9f0108fd6239e9d055e08e435af99b8ab0f1fd01fcf075590203010001a3583056301d\
    0603551d1104163014820c7365727665722e6c6f63616c87040a000001301d0603551d250416301406082b06\
    01050507030106082b0601050507030230090603551d1304023000300b0603551d0f0404030205a0300d0609\
    2a864886f70d01010b05000382010100ba085377c6f5a0888bf78bcf2e0387e88a87161ce75f45ab87e0510c\
    864bdc401723761823f80d167a246f422d5cd14da99129edff7c02f43b39dccd6fadb9c8372dcaefb25a06a2\
    16068bc4d0a1d860385eedc4cfd78c7d71a10c99a944c13097ee43b3ad86a212f0d3f5af6098b11faba7360c\
    5900082899aac312e258ca906eba96b3c39037087069f7f67e0891623f5eef7488bd159ddf3356d63418c3d1\
    6d3adbf08cd3995f2cfafd9fe1fb363bc2f74ba67fc1ed39c93569afd746ef0266577ed4eaa2e2f78eb87147\
    6aa7bd907b0db2d0aeb9565369ddd28c46c08e4ecd9cdbcfde070d0fc7ef75a4496c12d2864287143a5f311f\
    e2607986a3d6752c";

/// Its authority: CN=server.local CA, valid 3650 days.
const AUTHORITY_HEX: &str = "\
    3082031930820201a00302010202080a0b0c0d0e0f1011300d06092a864886f70d01010b0500303a310b3009\
    0603550406130246523111300f060355040a0c084865696d64616c6c3118301606035504030c0f7365727665\
    722e6c6f63616c204341301e170d3236303130323033303430355a170d3335313233313033303430355a303a\
    310b30090603550406130246523111300f060355040a0c084865696d64616c6c3118301606035504030c0f73\
    65727665722e6c6f63616c20434130820122300d06092a864886f70d01010105000382010f003082010a0282\
    010100e6acdfd30274c495c0e7498e0205821f93dd5728243f0efff23e84dddde41463eb955af3be2750fac2\
    ffc809e1b33f000d72a1f989e49bb68c2aca7261c9eebce82183cad68a4baf6abf6ccd7d0d018f57506f682d\
    d9815ecdc84d333d6f650a7a377b220120902f92bbfd2346491bdf62c0db40a01506f35326bb810177886249\
    fefa0385e0fde12cd5a2e2659d64e0c444ded5296e4bfd9e9803722ccc7548176162265f921b801061407145\
    47eb1a0bcec4c1b02330f386f5919445b9a23fa19103a5e164020335cebac28066715661d08b2aaa414a8d99\
    4cf89e09dc79e07f9acd6e1a11d63c9f0108fd6239e9d055e08e435af99b8ab0f1fd01fcf075590203010001\
    a3233021300f0603551d130101ff040530030101ff300e0603551d0f0101ff040403020106300d06092a8648\
    86f70d01010b0500038201010070cfdba63c8d4ae4eeeb2ed6284b10e76c23a217bbda9b56c3f09cb8832be2\
    bdd1f3db02b70df01bd6c759a9eb36510cf804dfdd7d81e7d5b6de1d515568c56c509b1590240609df3c3510\
    349febbc2e3f27e261a56fb42bb65d9a6568804c2af3c56df83964785b1b40fe2592ee3cbc5a9e9e5256fd9d\
    13bf7b4a9695216358ea220be9f025e42d73c4580fcb17bbdc3f10f120a12823ec92cc243821486e4373d402\
    be59b74e20ed4db780f865f74ecaa35fab0139da6d055eb70e347f1e0657b47a37966e82739fb2b5e2af4900\
    2d650cbf3f230efb2a11256bfbb51f3d8615262693d940d8b88e56c54ed72688dd6932d26f362e3d27d64cbf\
    3aad99d7e0";

/// The leaf the authority signed, a 16-byte serial.
const SIGNED_LEAF_HEX: &str = "\
    308203533082023ba003020102021021212121212121212121212121212121300d06092a864886f70d01010b\
    0500303a310b30090603550406130246523111300f060355040a0c084865696d64616c6c3118301606035504\
    030c0f7365727665722e6c6f63616c204341301e170d3236303130323033303430355a170d32373031303230\
    33303430355a3037310b30090603550406130246523111300f060355040a0c084865696d64616c6c31153013\
    06035504030c0c7365727665722e6c6f63616c30820122300d06092a864886f70d01010105000382010f0030\
    82010a0282010100e6acdfd30274c495c0e7498e0205821f93dd5728243f0efff23e84dddde41463eb955af3\
    be2750fac2ffc809e1b33f000d72a1f989e49bb68c2aca7261c9eebce82183cad68a4baf6abf6ccd7d0d018f\
    57506f682dd9815ecdc84d333d6f650a7a377b220120902f92bbfd2346491bdf62c0db40a01506f35326bb81\
    0177886249fefa0385e0fde12cd5a2e2659d64e0c444ded5296e4bfd9e9803722ccc7548176162265f921b80\
    106140714547eb1a0bcec4c1b02330f386f5919445b9a23fa19103a5e164020335cebac28066715661d08b2a\
    aa414a8d994cf89e09dc79e07f9acd6e1a11d63c9f0108fd6239e9d055e08e435af99b8ab0f1fd01fcf07559\
    0203010001a3583056301d0603551d1104163014820c7365727665722e6c6f63616c87040a000001301d0603\
    551d250416301406082b0601050507030106082b0601050507030230090603551d1304023000300b0603551d\
    0f0404030205a0300d06092a864886f70d01010b050003820101002bcf567e0c3b2dd79f2514d639a77acb76\
    1c523418f2e6f99b5b5d1c1831fc46198b70bcf427518526f11eb7f3a896e7a8aafe62cd25e070a5e5e31a80\
    4867cca2df6281ff4333e70b44ff7a4f87a090b7e09ea8288bc0d6080624e168a8f45964c063f76173cafbae\
    9c13cc31b35a4ef615587b579cc76406a004b261d80234dafb315e1671015f043f2b2a35a1928f098389a71d\
    ec7a2b4f7f557bd2d22d1804164e8cadc64798855fefe2bd92c16f36cf89a8f9fe1e47f301df591d93715f0f\
    544dab4be2257bc133cc566f3af715cb81afa8ab3147b71d1b7a0c807e788c1b89ec0d02b83f6c13c8f55073\
    ce7accd0d3b6f85176d272478eff30043c8fdd";

/// 2026-01-02 03:04:05 UTC, the C# tests' moment.
const NOW: u64 = 1_767_323_045;

/// Seconds in a day.
const DAY: u64 = 86_400;

/// Days a leaf is valid.
const LEAF_DAYS: u64 = 365;

/// Days the authority is valid.
const AUTHORITY_DAYS: u64 = 3650;

/// Bits of one hexadecimal digit.
const NIBBLE_BITS: u32 = 4;

/// Base of a hexadecimal digit.
const RADIX: u32 = 16;

fn hex(text: &str) -> Vec<u8> {
    let digits: Vec<u8> = text
        .chars()
        .map(|digit| u8::try_from(digit.to_digit(RADIX).expect("hexadecimal")).expect("< 16"))
        .collect();
    digits
        .chunks(2)
        .map(|pair| (pair[0] << NIBBLE_BITS) | pair[1])
        .collect()
}

fn name(common_name: &str) -> Name {
    Name {
        common_name: common_name.to_owned(),
        organization: Some("Heimdall".to_owned()),
        country: Some("FR".to_owned()),
    }
}

fn leaf(serial: Vec<u8>) -> Spec {
    let address: IpAddr = "10.0.0.1".parse().expect("an address");
    Spec {
        subject: name("server.local"),
        not_before: NOW,
        not_after: NOW + LEAF_DAYS * DAY,
        serial,
        profile: Profile::TlsLeaf(vec![
            AltName::Dns("server.local".to_owned()),
            AltName::Ip(address),
        ]),
    }
}

fn authority() -> Spec {
    Spec {
        subject: name("server.local CA"),
        not_before: NOW,
        not_after: NOW + AUTHORITY_DAYS * DAY,
        serial: vec![0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11],
        profile: Profile::Authority,
    }
}

fn key() -> SigningKey {
    SigningKey::rsa_sha256(&hex(TEST_ONLY_RSA_PKCS8_HEX)).expect("the test key")
}

#[test]
fn a_self_signed_leaf_is_byte_for_byte_masters() {
    let serial = vec![0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x08];
    let der = cert::self_signed(&leaf(serial), &key()).expect("signed");
    assert_eq!(der, hex(SELF_SIGNED_HEX));
}

#[test]
fn an_authority_and_the_leaf_it_signs_are_byte_for_byte_masters() {
    let key = key();
    let der = cert::self_signed(&authority(), &key).expect("signed");
    assert_eq!(der, hex(AUTHORITY_HEX));
    let signed = cert::signed_by(&leaf(vec![0x21; 16]), &key, &authority(), &key).expect("signed");
    assert_eq!(signed, hex(SIGNED_LEAF_HEX));
}
