/*
 * Copyright 2026 Julien Bombled
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! The versions of the components the About page's "System" card names, as the C# names
//! its `WebView2` and SSH.NET: read by the build script from the workspace's `Cargo.lock`,
//! the versions this binary was built with, and handed to the page in a variable each. A
//! component the lock does not pin to one version is left out, never guessed. No
//! dependency: the build script compiles this file on its own.

/// The variable the build script sets to the version of iced, the window's toolkit.
pub const ICED_VERSION_VARIABLE: &str = "HEIMDALL_ICED_VERSION";

/// The variable the build script sets to the version of russh, the SSH client.
pub const RUSSH_VERSION_VARIABLE: &str = "HEIMDALL_RUSSH_VERSION";

/// The variable the build script sets to the version of `IronRDP`, the RDP client.
pub const IRONRDP_VERSION_VARIABLE: &str = "HEIMDALL_IRONRDP_VERSION";

/// Each component: its package's name in `Cargo.lock`, and the variable its version is in.
pub const COMPONENTS: [(&str, &str); 3] = [
    ("iced", ICED_VERSION_VARIABLE),
    ("russh", RUSSH_VERSION_VARIABLE),
    ("ironrdp", IRONRDP_VERSION_VARIABLE),
];

/// The header of a package's entry in `Cargo.lock`.
const PACKAGE_HEADER: &str = "[[package]]";

/// The keys of an entry's name and version.
const NAME_KEY: &str = "name";
const VERSION_KEY: &str = "version";

/// The version `lock`, the text of a `Cargo.lock`, pins `package` to; `None` when it does
/// not hold the package, or holds it in more than one version: which one a component uses
/// is then not known here.
#[must_use]
pub fn locked_version(lock: &str, package: &str) -> Option<String> {
    let mut found: Option<&str> = None;
    for entry in lock.split(PACKAGE_HEADER).skip(1) {
        if value_of(entry, NAME_KEY) != Some(package) {
            continue;
        }
        let version = value_of(entry, VERSION_KEY)?;
        match found {
            Some(other) if other != version => return None,
            _ => found = Some(version),
        }
    }
    found.map(str::to_owned)
}

/// The quoted value of `key` in an entry, as `key = "value"`.
fn value_of<'a>(entry: &'a str, key: &str) -> Option<&'a str> {
    entry.lines().find_map(|line| {
        let (name, value) = line.split_once('=')?;
        if name.trim() != key {
            return None;
        }
        value.trim().strip_prefix('"')?.strip_suffix('"')
    })
}

#[cfg(test)]
mod tests {
    use super::locked_version;

    const LOCK: &str = r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "iced"
version = "0.14.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "iced_core",
]

[[package]]
name = "iced_core"
version = "0.14.1"

[[package]]
name = "rand"
version = "0.8.5"

[[package]]
name = "rand"
version = "0.9.2"
"#;

    #[test]
    fn a_package_locked_once_is_given_its_version() {
        assert_eq!(locked_version(LOCK, "iced").as_deref(), Some("0.14.0"));
        assert_eq!(locked_version(LOCK, "iced_core").as_deref(), Some("0.14.1"));
    }

    #[test]
    fn a_package_absent_or_in_two_versions_is_left_out() {
        assert_eq!(locked_version(LOCK, "russh"), None);
        assert_eq!(locked_version(LOCK, "rand"), None, "which one is not known");
        assert_eq!(locked_version("", "iced"), None);
    }

    #[test]
    fn the_lock_file_version_is_not_taken_for_a_package() {
        assert_eq!(locked_version(LOCK, "version"), None);
    }
}
